name: Publish to GitHub Packages

on:
  # Publish when you push a semver tag like v1.2.3
  push:
    tags:
      - "v*.*.*"
  # Manual trigger
  workflow_dispatch:

jobs:
  publish:
    name: Publish @erifystudio package
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write   # required to publish to GitHub Packages

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com
          scope: "@erifystudio"

      - name: Verify package scope matches @erifystudio
        run: |
          NAME=$(jq -r '.name' package.json)
          echo "package.json name: $NAME"
          if ! echo "$NAME" | grep -q '^@erifystudio/'; then
            echo "::error ::package.json name must be scoped to @erifystudio (e.g. \"@erifystudio/your-package\")"
            exit 1
          fi

      - name: Install dependencies (CI)
        run: npm ci

      - name: Run tests (if present)
        run: npm test --if-present

      - name: Build (if present)
        run: npm run build --if-present

      # Optional: ensure version in package.json matches tag (vX.Y.Z)
      - name: Check tag matches package.json version
        run: |
          TAG="${GITHUB_REF_NAME#v}"
          PKG_VER=$(jq -r '.version' package.json)
          echo "Tag: $TAG  package.json: $PKG_VER"
          if [ "$TAG" != "$PKG_VER" ]; then
            echo "::error ::Tag $TAG does not match package.json version $PKG_VER"
            exit 1
          fi

      - name: Configure npm auth for GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat << 'EOF' > ~/.npmrc
          @erifystudio:registry=https://npm.pkg.github.com
          //npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
          always-auth=true
          EOF

      - name: Publish to GitHub Packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --ignore-scripts=false
